### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by hilltty** [hraponssi/Sleeper#5]
1. Add the placeholder %player% to the "SleepInfo" message, which should display the nickname of the player who lay down on the bed and started the night skip
2. Add a custom cooldown for the player who lays down on the bed, this should fix spam messages

**Comment by hraponssi** [comment]
1. I'm not quite sure what you mean, as SleepInfo is sent to just the player that goes to sleep so it would be redundant to include their own username there (Unless that is what you want). NightSkip is sent when the night is skipped and has a %player% placeholder to show who triggered the skip.
2. I'm not sure what message would be spammed other than something like SleepInfo since that shows on bed entry, but that's only sent to the entering player. NightSkip is sent to everyone but it should only send once per skip.

**Comment by hilltty** [comment]
Oh, it seems to me that the message that someone lay down on the bed should be visible to everyone on the server, and so once for this message I suggested introducing a cooldown. This will be very useful because the players do not have to call others to lie down on the bed every time

**Comment by hilltty** [comment]
It's the same with the voting system, it's not worth it, as for me, to send a message about the start of voting every time.

Now I will try to paint the logic that would be as convenient as possible.
- You can start voting when one of the players lies down on the bed, while the player who lay down immediately votes for "yes"
- Further, instead of sending a vote message every time, use the boss bar to count
- Also, any player can lie on the bed, thereby voting for "yes"
- After a player has voted for any of the options, he cannot lie down on the bed

**Comment by hraponssi** [comment]
Added these as config options in 1.4.1.
